// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_trpc_path_ from "./routes/api/trpc/[...path].ts";
import * as $index from "./routes/index.tsx";
import * as $Account from "./islands/Account.tsx";
import * as $Navigation from "./islands/Navigation.tsx";
import * as $TrpcPlayground from "./islands/TrpcPlayground.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/trpc/[...path].ts": $api_trpc_path_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Account.tsx": $Account,
    "./islands/Navigation.tsx": $Navigation,
    "./islands/TrpcPlayground.tsx": $TrpcPlayground,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
